// Base product interface (used for reading)
export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviewCount: number;
  image: string;
  description: string;
  inStock: boolean;
  category: string;
  createdAt?: Date;
  updatedAt?: Date;
}

// Interface for creating a new product (id is optional as it's generated by the server)
export interface ProductCreate extends Omit<Product, 'id' | 'rating' | 'reviewCount' | 'discount'> {
  id?: never; // Ensure id is not provided when creating
  rating?: never;
  reviewCount?: never;
  discount?: never;
}

// Interface for updating a product (all fields optional except id)
export interface ProductUpdate extends Partial<Omit<Product, 'id'>> {
  id: number; // Required for updates
}

export interface CartItem extends Product {
  quantity: number;
  addedAt: Date;
}

export interface RatingUpdate {
  productId: number;
  rating: number;
  userId?: string; // Optional user ID for tracking who rated
}

export interface CartUpdate {
  productId: number;
  quantity: number;
}

export interface ProductResponse {
  success: boolean;
  data?: Product | Product[];
  error?: string;
  message?: string;
}
