// Base product interface (used for reading)
export interface Product {
  id: string;              
  name: string;
  price_cents: number;
  currency: string;
  description: string;
  image_url: string | null;
  category_id: string;
  slug: string;
  created_at: string;
  
  // Phase 1: Essential fields
  status?: 'active' | 'inactive' | 'draft' | 'archived';
  original_price_cents?: number | null;
  stock_quantity?: number;
  sku?: string | null;
  updated_at?: string;
  
  // Phase 2: Additional fields
  image_urls?: string[]; // JSONB array
  thumbnail_url?: string | null;
  brand_id?: string | null;
  is_featured?: boolean;
  is_new?: boolean;
  short_description?: string | null;
  
  // Phase 3: SEO & Marketing
  meta_title?: string | null;
  meta_description?: string | null;
  tags?: string[]; // JSONB array
  
  // Phase 3: Ratings
  rating?: number;
  review_count?: number;
  
  // Phase 3: Inventory
  low_stock_threshold?: number;
  track_inventory?: boolean;
  allow_backorders?: boolean;
  
  // Phase 3: Shipping
  weight_grams?: number | null;
  dimensions?: {
    length?: number;
    width?: number;
    height?: number;
    unit?: string;
  } | null;
}

// Product Variant interface
export interface ProductVariant {
  id: string;
  product_id: string;
  name: string;
  sku: string | null;
  color: string | null;
  size: string | null;
  price_cents: number | null;
  stock_quantity: number;
  image_url: string | null;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

// Product Review interface
export interface ProductReview {
  id: string;
  product_id: string;
  user_id: string | null;
  rating: number;
  title: string | null;
  comment: string | null;
  is_verified_purchase: boolean;
  helpful_count: number;
  created_at: string;
  updated_at: string;
}

// Interface for creating a new product (id is optional as it's generated by the server)
export interface ProductCreate extends Omit<Product, 'id' | 'rating' | 'reviewCount' | 'discount'> {
  id?: never; // Ensure id is not provided when creating
  rating?: never;
  reviewCount?: never;
  discount?: never;
}

// Interface for updating a product (all fields optional except id)
export interface ProductUpdate extends Partial<Omit<Product, 'id'>> {
  id: string; // Required for updates (UUID)
}

export interface CartItem extends Product {
  cartKey: string;
  quantity: number;
  addedAt: string;
  selectedColor?: string;
  selectedSize?: string;
}

export interface RatingUpdate {
  productId: number;
  rating: number;
  userId?: string; // Optional user ID for tracking who rated
}

export interface CartUpdate {
  productId: number;
  quantity: number;
}

export interface ProductResponse {
  success: boolean;
  data?: Product | Product[];
  error?: string;
  message?: string;
}
